//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShoutApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeDate
    {
        public int CoffeeDateNo { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Venue { get; set; }
        public string ShoutedBy { get; set; }
        public Nullable<decimal> ShoutedAmount { get; set; }
        public Nullable<int> IsPending { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
